export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f2f5fc",
    padding: "32px 16px",
    fontFamily: "'Avenir Next', 'Segoe UI', system-ui, sans-serif",
    color: "#1c2540",
  },
  container: { maxWidth: 720, margin: "0 auto" },
  title: {
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: 32,
    fontWeight: 600,
    margin: 0,
    letterSpacing: "-0.5px",
    lineHeight: 1.15,
    color: "#101a38",
  },
  subtitle: { color: "#6b7a99", fontSize: 14, marginTop: 6 },
  billingDaySelect: {
    marginLeft: 6,
    padding: "2px 6px",
    borderRadius: 6,
    border: "1px solid #c3d0ec",
    background: "#fff",
    fontSize: 13,
    color: "#1c2540",
  },
  summaryCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 32,
    background: "linear-gradient(135deg, #2a4a94 0%, #3d6bce 100%)",
    color: "#eef3ff",
    borderRadius: 14,
    padding: "24px 24px",
    marginBottom: 18,
    flexWrap: "wrap",
  },
  summaryItem: { textAlign: "center" },
  verticalDivider: {
    width: 1,
    alignSelf: "stretch",
    background: "rgba(238,243,255,0.25)",
  },
  label: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    opacity: 0.75,
    marginBottom: 4,
  },
  fieldLabel: {
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    color: "#5a6a90",
    marginBottom: 4,
  },
  bigFigure: {
    fontSize: 24,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
  },
  tabs: {
    display: "flex",
    gap: 6,
    marginBottom: 18,
    borderBottom: "2px solid #dbe4f5",
  },
  tab: {
    background: "transparent",
    border: "none",
    padding: "10px 16px",
    fontSize: 14,
    fontWeight: 600,
    color: "#6b7a99",
    cursor: "pointer",
    borderBottom: "3px solid transparent",
    marginBottom: -2,
  },
  tabActive: {
    color: "#3d6bce",
    borderBottom: "3px solid #3d6bce",
  },
  primaryButton: {
    background: "#3d6bce",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "7px 14px",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 600,
  },
  secondaryButton: {
    background: "transparent",
    color: "#3a4a70",
    border: "1px solid #c3d0ec",
    borderRadius: 8,
    padding: "7px 14px",
    fontSize: 14,
    cursor: "pointer",
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(16,26,56,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
    padding: 16,
  },
  modal: {
    background: "#fff",
    borderRadius: 14,
    padding: 24,
    maxWidth: 480,
    width: "100%",
    boxShadow: "0 20px 50px rgba(16,26,56,0.25)",
  },
  chartCard: {
    background: "#fff",
    border: "1px solid #dbe4f5",
    borderRadius: 14,
    padding: 20,
  },
  form: {
    background: "#fff",
    border: "1px solid #dbe4f5",
    borderRadius: 14,
    padding: 20,
    marginTop: 4,
  },
  formTitle: {
    fontFamily: "Georgia, serif",
    fontSize: 20,
    margin: "0 0 14px",
    color: "#101a38",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: 14,
  },
  field: { display: "flex", flexDirection: "column", gap: 4 },
  input: {
    padding: "9px 12px",
    borderRadius: 8,
    border: "1px solid #c3d0ec",
    fontSize: 15,
    background: "#f7f9fe",
    color: "#1c2540",
  },
  error: { color: "#c23a3a", fontSize: 14, marginTop: 10, marginBottom: 0 },
  purchaseCard: {
    display: "flex",
    gap: 16,
    background: "#fff",
    border: "1px solid #dbe4f5",
    borderRadius: 14,
    padding: "16px 18px",
  },
  purchaseName: { fontSize: 17, fontWeight: 600, margin: 0 },
  completedBadge: {
    fontSize: 11,
    background: "#e2e9f8",
    color: "#3a4a70",
    borderRadius: 999,
    padding: "2px 10px",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  newBadge: {
    fontSize: 11,
    background: "#e9f0fb",
    color: "#3d6bce",
    borderRadius: 999,
    padding: "2px 10px",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  detail: { fontSize: 13, color: "#6b7a99", margin: "4px 0 8px" },
  progressTrack: {
    height: 6,
    background: "#e4ebf8",
    borderRadius: 999,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    borderRadius: 999,
    transition: "width 0.4s ease",
  },
  rightSide: { textAlign: "right", flexShrink: 0 },
  installment: {
    fontSize: 19,
    fontWeight: 700,
    fontVariantNumeric: "tabular-nums",
  },
  miniButton: {
    background: "#f2f5fc",
    border: "1px solid #c3d0ec",
    borderRadius: 8,
    padding: "4px 8px",
    cursor: "pointer",
    fontSize: 13,
  },
};
